export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_EBOOK_SHOW = 'SET_EBOOK_SHOW';
export const FETCH_ONE_EBOOK_SUCCESS = 'FETCH_ONE_EBOOK_SUCCESS'; 
export const FETCH_EBOOKS_SUCCESS = 'FETCH_EBOOK_SUCCESS'; 
export const FETCH_EBOOK_FAILURE = 'FETCH_EBOOK_FAILURE'; 
